[build]
  command = "npm run build"
  publish = "dist"
  node_version = "22.10.x" 


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/p5/*"
[headers.values]
Access-Control-Allow-Origin = "*"